// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SentimentRazorML.Model
{
    public class ModelInput
    {
        [ColumnName("SentimentText"), LoadColumn(0)]
        public string SentimentText { get; set; }


        [ColumnName("Sentiment"), LoadColumn(1)]
        public bool Sentiment { get; set; }


    }
}
